options:
  formatter: stylish
  merge-default-rules: false
files:
  include: 'css/**/*.s+(a|c)ss'
  ignore: 'css/**/vendor/**/*.s+(a|c)ss'
rules:
  border-zero:
    - 2
    -
      convention: 0
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: true
  empty-args:
    - 2
    -
      include: false
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  leading-zero:
    - 2
    -
      include: true
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    -
      exclude:
        - display
        - src
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-trailing-zero: 2
  no-transition-all: 2
  one-declaration-per-line: 2
  property-sort-order:
    - 2
    -
      order: concentric
      ignore-custom-properties: false
  quotes:
    - 2
    -
      style: single
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit:
    - 2
    -
      include: false
